/**
 * api/pdf-to-png.js
 * VASA - Virtual Assistant SOC Arjawinangun
 * Vercel endpoint untuk screenshot Google Sheets data.
 * 
 * ARSITEKTUR:
 * - Cloudflare Worker fetch data dari Google Sheets API
 * - Kirim data JSON (rows) ke endpoint ini
 * - Vercel render sebagai HTML table + screenshot PNG
 * - Tidak perlu PDF conversion, tidak perlu pdfjs-dist
 * 
 * Request: POST JSON { sheet_title, rows: [[cell, ...], ...], scale }
 * Response: image/png
 */

import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';

export const config = {
  runtime: 'nodejs'
};

function escapeHtml(text) {
  return String(text || '')
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, '&#039;');
}

function renderSheetAsHtml(title, rows) {
  if (!rows || rows.length === 0) {
    return `<html><body><p>Tidak ada data</p></body></html>`;
  }

  const maxCols = Math.max(...rows.map(r => r.length));

  let html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { 
    font-family: 'Segoe UI', Arial, sans-serif; 
    background: #ffffff; 
    padding: 0;
    width: max-content;
    min-width: 800px;
  }
  .container { padding: 16px; }
  .header {
    background: linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%);
    color: white;
    padding: 14px 20px;
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 0;
  }
  .sheet-title {
    font-size: 14px;
    opacity: 0.9;
    font-weight: 400;
    margin-top: 4px;
  }
  table {
    border-collapse: collapse;
    width: 100%;
    border: 1px solid #dadce0;
  }
  th, td {
    border: 1px solid #e8eaed;
    padding: 10px 14px;
    text-align: left;
    font-size: 13px;
    white-space: nowrap;
    max-width: 300px;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  th {
    background: #f8f9fa;
    font-weight: 600;
    color: #3c4043;
    border-bottom: 2px solid #dadce0;
  }
  td { color: #202124; }
  tr:nth-child(even) td { background: #f8f9fa; }
  tr:hover td { background: #e8f0fe; }
  .footer {
    margin-top: 12px;
    font-size: 11px;
    color: #9aa0a6;
    text-align: right;
  }
</style>
</head>
<body>
<div class="container">
<div class="header">📊 ${escapeHtml(title)}
<div class="sheet-title">${rows.length} baris data</div>
</div>
<table>
<thead><tr>`;

  // Header row
  if (rows.length > 0) {
    for (let i = 0; i < maxCols; i++) {
      html += `<th>${escapeHtml(rows[0][i] || '')}</th>`;
    }
    html += '</tr></thead><tbody>';
    // Data rows
    for (let r = 1; r < rows.length; r++) {
      html += '<tr>';
      for (let c = 0; c < maxCols; c++) {
        html += `<td>${escapeHtml(rows[r][c] || '')}</td>`;
      }
      html += '</tr>';
    }
    html += '</tbody>';
  }

  html += `</table>
<div class="footer">Generated by VASA • ${new Date().toLocaleString('id-ID', { timeZone: 'Asia/Jakarta' })}</div>
</div>
</body></html>`;

  return html;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  let browser;

  try {
    const { sheet_title = "Spreadsheet", rows = [], scale = 2 } = req.body || {};

    if (!rows || rows.length === 0) {
      return res.status(400).json({ error: 'rows wajib diisi dan tidak boleh kosong.' });
    }

    const scaleFactor = Math.max(1, Math.min(Number(scale) || 2, 4));

    console.log(`Processing sheet: "${sheet_title}", ${rows.length} rows, scale ${scaleFactor}`);

    // STEP 1: Render data sebagai HTML table
    const htmlContent = renderSheetAsHtml(sheet_title, rows);

    // STEP 2: Screenshot HTML menggunakan Puppeteer
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH || (await chromium.executablePath()),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
      defaultViewport: {
        width: 1440,
        height: 900,
        deviceScaleFactor: scaleFactor
      }
    });

    const pageHandle = await browser.newPage();
    await pageHandle.setViewport({
      width: 1440,
      height: 900,
      deviceScaleFactor: scaleFactor
    });

    // Render HTML sebagai data URL (tanpa file:// dependency)
    const dataUrl = 'data:text/html;charset=utf-8,' + encodeURIComponent(htmlContent);
    await pageHandle.goto(dataUrl, { waitUntil: 'networkidle0', timeout: 30000 });

    await new Promise(resolve => setTimeout(resolve, 500));

    const pngBuffer = await pageHandle.screenshot({
      type: 'png',
      fullPage: true,
      omitBackground: false
    });

    console.log(`Screenshot generated: ${pngBuffer.length} bytes`);

    return res
      .status(200)
      .setHeader('Content-Type', 'image/png')
      .send(pngBuffer);
  } catch (error) {
    console.error('Screenshot error:', error);
    return res.status(500).json({ error: error?.message || 'Gagal membuat screenshot.' });
  } finally {
    if (browser) {
      await browser.close().catch(() => undefined);
    }
  }
}